aurora-is-near/borealis-engine-lib

refiner-app/src/cli.rs, refiner-app/src/main.rs, refiner-app/src/store.rs, refiner-lib/src/lib.rs, refiner-lib/src/refiner.rs
This feature is useful for debugging. For example to download a single block.
=> [feat]: Add total blocks to download optionally

.github/workflows/rust.yml, Cargo.lock, README.md, engine/Cargo.toml, engine/src/sync.rs, engine/src/types.rs, refiner-app/Cargo.toml, refiner-lib/Cargo.toml, refiner-lib/src/legacy.rs, refiner-lib/src/metrics.rs, refiner-lib/src/near_stream.rs, refiner-lib/src/refiner_inner.rs, refiner-lib/src/storage.rs, refiner-types/Cargo.toml, rust-toolchain
There are a number of fixes to Aurora Engine in version 2.8.0, including some that prevent possible crashes in Borealis Engine. In this PR we update to the new Engine version.
The new engine version also introduced some new top-level contract methods, so those are now also included in the `TransactionKind` enum.
This change also requires updating the `near-indexer` version because we need a common rocksdb version dependency (due to it using a sys library under the hood). The rust-toolchain version also needed to be increased because the Aurora Engine is now using a language feature that is unstable in Rust v1.61.
=> Chore: Update Aurora Engine to version 2.8.0

Cargo.lock, Cargo.toml, engine/Cargo.toml, refiner-app/Cargo.toml, refiner-lib/Cargo.toml, refiner-types/Cargo.toml
Uses the recent [cargo feature](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table) to avoid duplicating the version of our dependencies in multiple Cargo.toml files. This make changing those versions across all crates in the workspace much easier going forward.
=> Chore: Avoid duplicating dependency versions using workspace inheritance

Cargo.lock, Cargo.toml, engine/src/lib.rs, engine/src/tests.rs, refiner-app/src/input/data_lake.rs, refiner-lib/Cargo.toml, refiner-types/src/lib.rs
PR updates some dependencies and re-export the `errors` module from the `near-primitive` crate.
@birchmd pay attention please if the bumping dependencies won't break other crates.
=> chore: update some dependencies and re-export errors module

Cargo.lock, Cargo.toml
I got ahead of myself updating the `near-indexer` to such a recent commit hash. Using that late of a version created an issue where the node would not connect to peers due to breaking changes in NEAR's networking protocol. However, as I mentioned in the PR where I moved to that recent commit hash, the current 1.30 release canadiate cannot be used with Aurora Engine 2.8.1 due to conflicting versions of rocksdb. The solution is to make a custom release of our own where we have taken NEAR's 1.30 release candidate and cherry-picked the commit for the [rocksdb version bump in NEAR](https://github.com/near/nearcore/pull/7731).
Once NEAR updates rocksdb in one of their releases then we can go back to an official release. I [asked about this in …
=> Chore: use near-indexer from 1.30 release

refiner-lib/src/refiner_inner.rs, refiner-lib/src/utils.rs, refiner-types/src/aurora_block.rs
The go-ethereum implementation of the transaction and block types uses u64 for these quantities. We should follow suit for compatibility reasons.
=> Fix(types): Use u64 for gas a nonce types

Cargo.lock, refiner-app/Cargo.toml, refiner-app/src/store.rs
Fixes #33 
This PR changes the logic for saving the last processed block height to a file so that it writes to a new file and then moves onto the main file. This ensures the main file is atomically updated (there is never a state where the file is cleared, but not yet written to).
=> Fix(refiner): Atomically update last block file

Cargo.lock, Cargo.toml, default_config.json, refiner-app/src/config.rs, refiner-app/src/main.rs, refiner-lib/Cargo.toml, refiner-lib/src/lib.rs, refiner-lib/src/metrics.rs, refiner-lib/src/near_stream.rs, refiner-lib/src/refiner.rs, refiner-lib/src/refiner_inner.rs, refiner-lib/src/tx_hash_tracker.rs, refiner-types/src/aurora_block.rs, refiner-types/src/lib.rs
The bridge needs to know the NEAR transaction hash for each Aurora transaction; the NEAR receipt hash is not good enough for their system. This PR introduces a new stateful component to the Refiner which keeps track of the transaction hash for each receipt. This is needed because there is no way to correlate receipt hashes with transaction hashes using the information available from a single block, therefore we must build up this relationship as we consume blocks.
This has a few impacts to users of the Refiner and its output:
1. There is a new config field to set the directory where the receipt/transaction mapping data will be stored on-disk (we store it on disk so that it is still present after restart).
2. There is now a `transaction_hash` field that is part of the `near_metadata` of …
=> Feat(refiner): Track the transaction hash the caused each receipt to be created

refiner-lib/src/refiner_inner.rs
The issue @spilin encountered with the refiner was triggered by the internal Engine instance not having the proper state to use. This resulted in it computing incorrect outcomes and the refiner used to use these outcomes directly without checking the Near outcome first. This PR makes a few important changes:
1. The `build_transaction` function is only given a Near outcome for the last action in each Near receipt. This is correct because the outcome of a Near receipt only comes from the last action in the batch; for all other actions their outcomes are not recorded by Near.
2. In the case that the Near outcome is available (i.e. for the last action in each receipt), this outcome is used to set the transaction values. This means the refiner will produce correct output even if its Engine …
=> Fix(refiner): Check Near and Engine outcomes match

engine/src/tracing/alchemy/conversion/mod.rs
In #36 I neglected to make the fields for `TransactionContext` public, which meant that the object could not be constructed by other crates using this library. This PR fixes the issue.
=> Fix(engine-tracing): Public fields on TransactionContext

engine/src/sync.rs, refiner-lib/src/near_stream.rs, refiner-lib/tests/res/block-84423722.json
This PR fixes a bug where the Refiner (and Engine) would crash on receipts that contain zero actions. A new test is added for this case. I also factored out common test setup into a struct to reduce code duplication between tests.
=> Fix: refiner can process receipts with no actions

refiner-app/src/config.rs, refiner-app/src/main.rs
Adding non-optional field to the config is a breaking change to partners (we cannot update their configs remotely). In this PR the new field for the transaction tracker is made optional, with the default value being a sub-directory of the engine storage.
=> Fix: configuring the transaction tracker path is optional

refiner-app/src/store.rs
Some text editors will automatically add whitespace at the end of a file and this can cause an issue when manually editing `.REFINER_LAST_BLOCK`. The PR fixes the issue.
=> Fix: ignore whitespace in last block file

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, engine/Cargo.toml, engine/src/sync.rs, engine/src/types.rs, refiner-lib/src/metrics.rs, refiner-lib/src/near_stream.rs, refiner-lib/src/refiner_inner.rs, refiner-lib/tests/res/testnet-block-120572296.json, rust-toolchain
The primary goal of this PR is to make the refiner handle the new `DelegateAction` Near introduced to support [meta-transacions.](https://github.com/near/NEPs/blob/master/neps/nep-0366.md). In trying to do this I also needed to update the Aurora Engine dependency (since nearcore moved to borsh version 0.10 and so the Engine had to do this also). The latest version of the Engine also has new methods (transaction kinds), which this PR also enables support for.
=> Chore: update Engine and Near dependencies (support DelegateAction)

Cargo.lock, engine/Cargo.toml, refiner-app/Cargo.toml, refiner-lib/Cargo.toml, refiner-types/Cargo.toml
Updates to 0.19.2 (0.19.1 is already released and tagged, so we'll skip that one in Cargo.toml since we're about to make the 0.19.2 release anyway).
=> Chore: Update Cargo.toml to current release version

Cargo.lock, Cargo.toml, engine/src/batch_tx_processing.rs, engine/src/lib.rs, engine/src/sync.rs
This fix address the performance issue in the refiner where constantly writing and deleting the same key made reading that key slow. Now the diff of a transaction is checked before committing it to the DB so that only the correct diff is written. Related PR: https://github.com/aurora-is-near/aurora-engine/pull/825
=> Fix: check diff before commiting it to storage

Cargo.lock, Cargo.toml
I was using an unmerged commit in PR #95 , and the commit hash changed after merging due to the squash merge on Aurora Engine. This PR updates to the correct Aurora Engine commit.
This PR also includes the change to bump webpki from 0.22.0 to 0.22.1 as suggested in #96
=> Chore(deps): Update Aurora Engine to commit aa20b0c

Cargo.lock, Cargo.toml, engine/src/lib.rs, etc/integration-tests/Cargo.toml, refiner-types/Cargo.toml, refiner-types/src/lib.rs
The PR rollback adding re-export because it will be redundant in case of monorepo.
=> chore: bump aurora-engine to 3.3.1 and remove re-exports

Cargo.lock, Cargo.toml, engine/src/res/block_105089746.json, engine/src/sync.rs, engine/src/tests.rs
This PR updates to the latest (not yet released) Aurora Engine dependency which includes a fix to how the random seed exposed from Near runtime is computed. As part of this fix each transaction now has an `action_hash` associated with it. This field is now computed by Borealis Engine from Near block data.
I also added a test to replay a [transaction from mainnet](https://nearblocks.io/txns/HSBuxbzFnkKp3mrhwXXv22oytY4wSNRebsghC6DdLPJs#execution) where I call the random value precompile to make sure the new logic computes the same value as on-chain.
=> Fix(engine): Compute action_hash for each transaction

refiner-app/src/socket.rs, refiner-lib/src/metrics.rs
The PR adds a new label with a service version to the prometheus metrics. E.g. of the output:
```
refiner_near_listener_processed_blocks{version="0.25.0"} 548
refiner_near_listener_skip_blocks{version="0.25.0"} 13501
refiner_number_of_latest_block_processed{version="0.25.0"} 14049
```
=> feat: add label with version to prometheus metrics

Cargo.lock, Cargo.toml
In this PR I'm starting to use a new versioning schema for our borealis releases. We use semver standard to include both our `VERSION` and after + `NEARCORE_VERSION`. Tagging and realising will follow the same policy.
Nearcore version is represented by https://semver.org/#spec-item-10 (build information) extension.
=> chore: bump nearcore to 1.38.0

Cargo.lock, Cargo.toml
Rust package version is using "0.28.1+1.38.1" notation to add build information, but github tag and docker build will use "0.28.1-1.38.1" notation to support dockerhub taging policy. This is a subject for discussion in the future.
=> chore: bump nearcore to 1.38.1

Cargo.lock, Cargo.toml, engine/src/sync.rs, rust-toolchain
This `nearcore` update also brings multiple dependecies' versions update + `rustc` update + a change to `near_primitives::views::ReceiptEnumView::Data` interface
=> chore: bump nearcore to 1.40.0-rc.1

Cargo.lock, Cargo.toml, engine/src/tracing/alchemy/serialization.rs, refiner-lib/src/near_stream.rs, refiner-lib/src/refiner_inner.rs, refiner-types/Cargo.toml, refiner-types/src/near_block.rs, rust-toolchain
[x] Update nearcore version
[x] Updates Rust to 1.78 (new clippy lints)
[x] Support `priority_fee` from https://github.com/near/nearcore/commit/a9a6eff1121dc48c4aa6a0e4891ef29542e41b84 (SUPPORT FOR BLOCKS WITHOUT `priority` HAS BEEN DROPPED)
=> chore: bump nearcore to 2.0.0-rc.1

Cargo.lock, Cargo.toml, refiner-app/src/conversion/mod.rs, refiner-app/src/socket.rs, refiner-lib/src/tx_hash_tracker.rs, refiner-types/src/aurora_block.rs, refiner-types/src/near_block.rs, refiner-types/src/utils.rs, rust-toolchain
Reason for updating the Rust toolchain to 1.82.0
A `borealis-engine-lib` build pointing to `nearcore` [2.4.0-rc.1](https://github.com/near/nearcore/releases/tag/2.4.0-rc.1) has failed due to a version conflict between the `syn` crate versions required by different dependencies:
1. `thiserror-impl` v2.0.0 requires syn ^2.0.87.
2. `actix-macros` v0.2.4 requires syn ^2.0.79.
```
borealis-engine-lib % cargo check
Updating git repository `https://github.com/near/nearcore`
Updating crates.io index
error: failed to select a version for `syn`.
... required by package `thiserror-impl v2.0.0`
... which satisfies dependency `thiserror-impl = "=2.0.0"` of package `thiserror v2.0.0`
... which satisfies dependency `thiserror = "^2.0"` of package `near-crypto v2.4.0-rc.1 …
```
=> chore: bump nearcore to 2.4.0 rc.1, Rust toolchain to 1.82.0

Cargo.lock
This PR contains only Cargo.lock changes because the nearcore 2.4.0 release was updated to point to a new commit.
=> chore: updated nearcore 2.4.0 deps

Cargo.lock, Cargo.toml, refiner-app/src/input/nearcore.rs, refiner-types/Cargo.toml, rust-toolchain
NOTE:
The reason for adding the dev feature is due to the following warning:
```
> cargo check
warning: unexpected `cfg` condition value: `dev`
--> refiner-types/src/bloom.rs:14:1
|
14 | / construct_fixed_hash! {
15 | |     /// Bloom hash type with 256 bytes (2048 bits) size.
16 | |     pub struct Bloom(BLOOM_SIZE);
17 | | }
| |_^
|
= note: expected values for `feature` are: `ext-connector`
= help: consider adding `dev` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
= note: `#[warn(unexpected_cfgs)]` on by default
= note: this warning originates in the macro `construct_fixed_hash` (in Nightly builds, run with -Z macro-backtrace for more info)
```
=> Chore/nearcore 2.5.0 rc.1

Cargo.lock, Cargo.toml, refiner-lib/Cargo.toml, refiner-lib/build.rs, refiner-lib/src/metrics.rs
This PR fixes a version value assigned to the metrics labels.
The version function outputs `{CARGO_PKG_VERSION}-{VERGEN_GIT_SHA}`
If `CARGO_PKG_VERSION` is not set at runtime, it returns to the `CARGO_PKG_VERSION` available at compile time.
If `VERGEN_GIT_SHA` is not set, use `CARGO_PKG_VERSION` as is.
=> Read proper package version as a source of the service version

Cargo.lock, Cargo.toml, engine/src/batch_tx_processing.rs, engine/src/gas.rs, engine/src/lib.rs, engine/src/sync.rs, engine/src/tests.rs, engine/src/tracing/alchemy/conversion/mod.rs, engine/src/tracing/alchemy/conversion/tests.rs, engine/src/tracing/alchemy/mod.rs, engine/src/tracing/alchemy/serialization.rs, engine/src/tracing/lib.rs, etc/integration-tests/src/nearcore_utils.rs, refiner-app/src/conversion/mod.rs, refiner-app/src/socket.rs, refiner-lib/src/hashchain.rs, refiner-lib/src/lib.rs, refiner-lib/src/metrics.rs, refiner-lib/src/near_stream.rs, refiner-lib/src/refiner_inner.rs, refiner-lib/src/storage.rs, refiner-types/src/aurora_block.rs, refiner-types/src/lib.rs, refiner-types/src/utils.rs, rust-toolchain
- Updated nearcore to 2.5.0;
- Use toolchain 1.85.0;
- Use Rust edition 2024.
=> chore: Bump nearcore to 2.5.0

CHANGES.md, Cargo.lock, Cargo.toml
- Temporary pin the `tempfile` crate to version 3.14 due to [issue 12944](https://github.com/near/nearcore/issues/12944#issuecomment-2707438357)
=> fix: Temporary pin the `tempfile` crate to version 3.14

.github/workflows/rust.yml, CHANGES.md, Cargo.lock, Cargo.toml, engine/src/gas.rs, engine/src/sync.rs, refiner-lib/src/metrics.rs, refiner-lib/src/refiner_inner.rs
This PR includes:
- Bump `aurora-engine` to `3.9.0`;
- Bump `nearcore` to `2.6.0-rc.1`.
=> chore: bump aurora-engine to 3.9.0 and nearcore to 2.6.0-rc.1

Cargo.lock, refiner-app/src/input/data_lake.rs, refiner-app/src/input/nearcore.rs, refiner-app/src/main.rs, refiner-app/src/store.rs, refiner-lib/Cargo.toml, refiner-lib/src/signal_handlers.rs
In this PR:
1. Added coordinated explicit shutdown to the following tasks:
- Near Data Lake stream;
- Nearcore stream;
- AuroraBlocks stream.
2. Signal handlers reuse the system codes, instead of hardcoded values;
3. Added SIGQUIT handler.
=> fix: Coordinated shutdown for the input and output streams

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.1). New package version: 0.30.4-2.6.1
=> chore: Bump nearcore to 2.6.1

CHANGES.md, Cargo.lock, Cargo.toml
In this PR:
- Bump nearcore dependencies to 2.6.1-rc.1
=> chore: Bump nearcore to 2.6.1-rc.1

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.2-rc.1). New package version: 0.30.4-2.6.2-rc.1
=> chore: Bump nearcore to 2.6.2-rc.1

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.2). New package version: 0.30.4-2.6.2
=> chore: Bump nearcore to 2.6.2

.github/workflows/rust.yml, .github/workflows/update-nearcore.yml, Cargo.lock
This PR fixes outdated dependency versions.
In particular, `near-indexer-primitives` was pinned to version `0.28` (which lacked the `Use-` and `DeployGlobalContractId` actions), while the most recent version, `0.30.1`, includes the updated actions.
Changes:
- Updated `Cargo.lock` (by `cargo update`);
- Use `cargo update`, instead of `cargo check` when running CI job;
- On `self-hosted, heavy` runner use clang compiler;
=> fix: Updated Cargo.lock, use cargo update instead of cargo check

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.3-rc.1). New package version: 0.30.4-2.6.3-rc.1
=> chore: Bump nearcore to 2.6.3-rc.1

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.3-rc.2). New package version: 0.30.4-2.6.3-rc.2
=> chore: Bump nearcore to 2.6.3-rc.2

CHANGES.md, Cargo.lock, Cargo.toml
Automated update of nearcore dependencies to the latest nearcore release tag (2.6.3). New package version: 0.30.4-2.6.3
=> chore: Bump nearcore to 2.6.3

CHANGES.md, Cargo.lock, Cargo.toml, engine/src/sync.rs
In this PR
Lists the changes for **mainnet** since the lates mainnet release **(0.30.6-2.6.5)**
```
6e6e7d3 fix: receipt_execution_outcomes order (#240)
```
=> release 0.30.8-2.6.5 mainnet 
